export interface Restaurant {
  id: string;
  name: string;
  cuisine: string;
  region: string;
  lat: number;
  lng: number;
  photo: string;
  rating: number;
}

export const hardcodedRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "Barbarestan",
    cuisine: "Vegetarian",
    region: "Barbarestan",
    lat: 0, // TODO: Add real coordinates
    lng: 0,
    photo: "/placeholder.jpg", // TODO: Add real photo
    rating: 4.7, // Example rating
  },
  {
    id: "2",
    name: "Café Littera",
    cuisine: "Seafood",
    region: "Café Littera",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.6,
  },
  {
    id: "3",
    name: "Shavi Lomi",
    cuisine: "Seafood",
    region: "Shavi Lomi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "4",
    name: "Sakhli #11",
    cuisine: "European",
    region: "Sakhli #11",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "5",
    name: "Culinarium Khasheria",
    cuisine: "Seafood",
    region: "Culinarium Khasheria",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "6",
    name: "Amra Restaurant Batumi",
    cuisine: "Seafood",
    region: "Amra Restaurant Batumi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "7",
    name: "Wine Factory N1",
    cuisine: "Asian",
    region: "Wine Factory N1",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "8",
    name: "Machakhela",
    cuisine: "Georgian",
    region: "Machakhela",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "9",
    name: "Pasanauri",
    cuisine: "Asian",
    region: "Pasanauri",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "10",
    name: "Mapshalia Kutaisi",
    cuisine: "Traditional",
    region: "Mapshalia Kutaisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "11",
    name: "Tavaduri Kutaisi",
    cuisine: "Seafood",
    region: "Tavaduri Kutaisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "12",
    name: "Borjomi Central Restaurant",
    cuisine: "Seafood",
    region: "Borjomi Central Restaurant",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "13",
    name: "Old Boulevard Batumi",
    cuisine: "Vegetarian",
    region: "Old Boulevard Batumi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "14",
    name: "Sky Bar Nephele",
    cuisine: "Asian",
    region: "Sky Bar Nephele",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "15",
    name: "Garden Restaurant",
    cuisine: "Mediterranean",
    region: "Garden Restaurant",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "16",
    name: "Laguna Batumi",
    cuisine: "Fusion",
    region: "Laguna Batumi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "17",
    name: "Khinklis Sakhli #1",
    cuisine: "Traditional",
    region: "Khinklis Sakhli #1",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "18",
    name: "Cafe Gabriadze",
    cuisine: "Vegetarian",
    region: "Cafe Gabriadze",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "19",
    name: "Racha Dukhan",
    cuisine: "Vegetarian",
    region: "Racha Dukhan",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "20",
    name: "Old City Restaurant Kutaisi",
    cuisine: "Georgian",
    region: "Old City Restaurant Kutaisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "21",
    name: "Cafe Daphna",
    cuisine: "Traditional",
    region: "Cafe Daphna",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "22",
    name: "Keto and Kote",
    cuisine: "Traditional",
    region: "Keto and Kote",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "23",
    name: "Black Lion",
    cuisine: "Traditional",
    region: "Black Lion",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "24",
    name: "Shemoikhede Genatsvale",
    cuisine: "Vegetarian",
    region: "Shemoikhede Genatsvale",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "25",
    name: "Metekhis Chrdili",
    cuisine: "Georgian",
    region: "Metekhis Chrdili",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "26",
    name: "Cafe Leila",
    cuisine: "Traditional",
    region: "Cafe Leila",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "27",
    name: "Alubali Tbilisi",
    cuisine: "Seafood",
    region: "Alubali Tbilisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "28",
    name: "Organique Josper Bar",
    cuisine: "Fusion",
    region: "Organique Josper Bar",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "29",
    name: "Funicular Restaurant Complex",
    cuisine: "Georgian",
    region: "Funicular Restaurant Complex",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "30",
    name: "Old Garden Kutaisi",
    cuisine: "Fusion",
    region: "Old Garden Kutaisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "31",
    name: "Terrace Tbilisi",
    cuisine: "European",
    region: "Terrace Tbilisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "32",
    name: "Taglaura",
    cuisine: "Vegetarian",
    region: "Taglaura",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "33",
    name: "The Kitchen Tbilisi",
    cuisine: "Georgian",
    region: "The Kitchen Tbilisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "34",
    name: "Melograno Kutaisi",
    cuisine: "Vegetarian",
    region: "Melograno Kutaisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "35",
    name: "Fanfan Tbilisi",
    cuisine: "Vegetarian",
    region: "Fanfan Tbilisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "36",
    name: "Tavaduri Garden",
    cuisine: "Vegetarian",
    region: "Tavaduri Garden",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "37",
    name: "Sormoni",
    cuisine: "European",
    region: "Sormoni",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "38",
    name: "Retro Batumi",
    cuisine: "Asian",
    region: "Retro Batumi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "39",
    name: "Adjara House",
    cuisine: "Mediterranean",
    region: "Adjara House",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "40",
    name: "Porto Franco Batumi",
    cuisine: "Mediterranean",
    region: "Porto Franco Batumi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "41",
    name: "Cafe Flowers",
    cuisine: "Vegetarian",
    region: "Cafe Flowers",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "42",
    name: "Argo Restaurant",
    cuisine: "Asian",
    region: "Argo Restaurant",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "43",
    name: "Bina N37",
    cuisine: "Vegetarian",
    region: "Bina N37",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "44",
    name: "Zakhar Zakharich",
    cuisine: "European",
    region: "Zakhar Zakharich",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "45",
    name: "Cafe Moulin Electrique",
    cuisine: "Traditional",
    region: "Cafe Moulin Electrique",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "46",
    name: "Chashnagiri",
    cuisine: "Fusion",
    region: "Chashnagiri",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "47",
    name: "Metis Batumi",
    cuisine: "Georgian",
    region: "Metis Batumi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "48",
    name: "Chveni",
    cuisine: "Vegetarian",
    region: "Chveni",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "49",
    name: "Craft Wine Kutaisi",
    cuisine: "Mediterranean",
    region: "Craft Wine Kutaisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  {
    id: "50",
    name: "Savane Kutaisi",
    cuisine: "European",
    region: "Savane Kutaisi",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.5,
  },
  { id: "51", name: "Rustaveli Restaurant", cuisine: "Fusion", region: "Rustaveli Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "52", name: "Gardenia Café", cuisine: "Georgian", region: "Gardenia Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "53", name: "Europe House Café", cuisine: "Asian", region: "Europe House Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "54", name: "Meama Kitchen", cuisine: "Seafood", region: "Meama Kitchen", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "55", name: "Old Town Grill", cuisine: "Georgian", region: "Old Town Grill", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "56", name: "Puri Guliani", cuisine: "Vegetarian", region: "Puri Guliani", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "57", name: "Ajarian Wine House", cuisine: "Seafood", region: "Ajarian Wine House", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "58", name: "Taste of Georgia", cuisine: "Seafood", region: "Taste of Georgia", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "59", name: "Cafe Rustico", cuisine: "Seafood", region: "Cafe Rustico", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "60", name: "Beso Restaurant", cuisine: "Asian", region: "Beso Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "61", name: "Lagidze Water Café", cuisine: "European", region: "Lagidze Water Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "62", name: "Gorgasali Café", cuisine: "Asian", region: "Gorgasali Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "63", name: "Cafe Gallery", cuisine: "Mediterranean", region: "Cafe Gallery", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "64", name: "Sakhli 10", cuisine: "Fusion", region: "Sakhli 10", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "65", name: "Georgian Table", cuisine: "Mediterranean", region: "Georgian Table", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "66", name: "Urban Garden Café", cuisine: "Asian", region: "Urban Garden Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "67", name: "Delizia Restaurant", cuisine: "Fusion", region: "Delizia Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "68", name: "Café de Paris Tbilisi", cuisine: "Asian", region: "Café de Paris Tbilisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "69", name: "Ninia's Garden", cuisine: "Mediterranean", region: "Ninia's Garden", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "70", name: "Casa della Pasta", cuisine: "European", region: "Casa della Pasta", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "71", name: "Cafe Roma", cuisine: "Seafood", region: "Cafe Roma", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "72", name: "Gvino Underground", cuisine: "European", region: "Gvino Underground", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "73", name: "Kitchen & Wine", cuisine: "Mediterranean", region: "Kitchen & Wine", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "74", name: "Pizzeria Toscana", cuisine: "Georgian", region: "Pizzeria Toscana", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "75", name: "Marani Restaurant", cuisine: "Georgian", region: "Marani Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "76", name: "Bagrati Restaurant", cuisine: "European", region: "Bagrati Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "77", name: "Asia Fusion Kutaisi", cuisine: "Georgian", region: "Asia Fusion Kutaisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "78", name: "Utskho Restaurant", cuisine: "Vegetarian", region: "Utskho Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "79", name: "House of Wine Batumi", cuisine: "Fusion", region: "House of Wine Batumi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "80", name: "Fusion Garden", cuisine: "Traditional", region: "Fusion Garden", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "81", name: "Cafe Brasserie", cuisine: "Fusion", region: "Cafe Brasserie", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "82", name: "Qalaqi Restaurant", cuisine: "Mediterranean", region: "Qalaqi Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "83", name: "Park Lounge Batumi", cuisine: "Georgian", region: "Park Lounge Batumi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "84", name: "Cafe Mandarin", cuisine: "Seafood", region: "Cafe Mandarin", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "85", name: "Brew & Wine", cuisine: "Vegetarian", region: "Brew & Wine", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "86", name: "Vino Underground Kutaisi", cuisine: "Mediterranean", region: "Vino Underground Kutaisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "87", name: "Mimino Café", cuisine: "Georgian", region: "Mimino Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "88", name: "Ezo Restaurant", cuisine: "European", region: "Ezo Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "89", name: "Khareba Wine Restaurant", cuisine: "Georgian", region: "Khareba Wine Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "90", name: "Firewood Grill", cuisine: "Vegetarian", region: "Firewood Grill", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "91", name: "Urban Tbilisi Eatery", cuisine: "Seafood", region: "Urban Tbilisi Eatery", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "92", name: "Borani Restaurant", cuisine: "Mediterranean", region: "Borani Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "93", name: "Tifliso Garden", cuisine: "Fusion", region: "Tifliso Garden", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "94", name: "Dolci Cafe", cuisine: "Traditional", region: "Dolci Cafe", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "95", name: "Rustic Soul Café", cuisine: "European", region: "Rustic Soul Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "96", name: "Amber Wine Bar", cuisine: "Traditional", region: "Amber Wine Bar", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "97", name: "Sunset Café Batumi", cuisine: "Vegetarian", region: "Sunset Café Batumi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "98", name: "Café Antique", cuisine: "Seafood", region: "Café Antique", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "99", name: "Charme Tbilisi", cuisine: "Asian", region: "Charme Tbilisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "100", name: "Café Ninia", cuisine: "Seafood", region: "Café Ninia", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "101", name: "Rustaveli Restaurant", cuisine: "Seafood", region: "Rustaveli Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "102", name: "Gardenia Café", cuisine: "Vegetarian", region: "Gardenia Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "103", name: "Europe House Café", cuisine: "Georgian", region: "Europe House Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "104", name: "Meama Kitchen", cuisine: "Fusion", region: "Meama Kitchen", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "105", name: "Old Town Grill", cuisine: "Fusion", region: "Old Town Grill", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "106", name: "Puri Guliani", cuisine: "Vegetarian", region: "Puri Guliani", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "107", name: "Ajarian Wine House", cuisine: "Asian", region: "Ajarian Wine House", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "108", name: "Taste of Georgia", cuisine: "Traditional", region: "Taste of Georgia", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "109", name: "Cafe Rustico", cuisine: "Georgian", region: "Cafe Rustico", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "110", name: "Beso Restaurant", cuisine: "Georgian", region: "Beso Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "111", name: "Lagidze Water Café", cuisine: "European", region: "Lagidze Water Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "112", name: "Gorgasali Café", cuisine: "Traditional", region: "Gorgasali Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "113", name: "Cafe Gallery", cuisine: "Georgian", region: "Cafe Gallery", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "114", name: "Sakhli 10", cuisine: "Vegetarian", region: "Sakhli 10", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "115", name: "Georgian Table", cuisine: "European", region: "Georgian Table", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "116", name: "Urban Garden Café", cuisine: "Georgian", region: "Urban Garden Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "117", name: "Delizia Restaurant", cuisine: "Traditional", region: "Delizia Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "118", name: "Café de Paris Tbilisi", cuisine: "Mediterranean", region: "Café de Paris Tbilisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "119", name: "Ninia's Garden", cuisine: "European", region: "Ninia's Garden", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "120", name: "Casa della Pasta", cuisine: "European", region: "Casa della Pasta", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "121", name: "Cafe Roma", cuisine: "Georgian", region: "Cafe Roma", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "122", name: "Gvino Underground", cuisine: "Vegetarian", region: "Gvino Underground", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "123", name: "Kitchen & Wine", cuisine: "Mediterranean", region: "Kitchen & Wine", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "124", name: "Pizzeria Toscana", cuisine: "Georgian", region: "Pizzeria Toscana", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "125", name: "Marani Restaurant", cuisine: "Traditional", region: "Marani Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "126", name: "Bagrati Restaurant", cuisine: "Seafood", region: "Bagrati Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "127", name: "Asia Fusion Kutaisi", cuisine: "Asian", region: "Asia Fusion Kutaisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "128", name: "Utskho Restaurant", cuisine: "Georgian", region: "Utskho Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "129", name: "House of Wine Batumi", cuisine: "Asian", region: "House of Wine Batumi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "130", name: "Fusion Garden", cuisine: "Georgian", region: "Fusion Garden", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "131", name: "Cafe Brasserie", cuisine: "Asian", region: "Cafe Brasserie", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "132", name: "Qalaqi Restaurant", cuisine: "Georgian", region: "Qalaqi Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "133", name: "Park Lounge Batumi", cuisine: "European", region: "Park Lounge Batumi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "134", name: "Cafe Mandarin", cuisine: "Fusion", region: "Cafe Mandarin", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "135", name: "Brew & Wine", cuisine: "Mediterranean", region: "Brew & Wine", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "136", name: "Vino Underground Kutaisi", cuisine: "European", region: "Vino Underground Kutaisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "137", name: "Mimino Café", cuisine: "Fusion", region: "Mimino Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "138", name: "Ezo Restaurant", cuisine: "Seafood", region: "Ezo Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "139", name: "Khareba Wine Restaurant", cuisine: "Mediterranean", region: "Khareba Wine Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "140", name: "Firewood Grill", cuisine: "Georgian", region: "Firewood Grill", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "141", name: "Urban Tbilisi Eatery", cuisine: "Mediterranean", region: "Urban Tbilisi Eatery", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "142", name: "Borani Restaurant", cuisine: "Traditional", region: "Borani Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "143", name: "Tifliso Garden", cuisine: "Fusion", region: "Tifliso Garden", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "144", name: "Dolci Cafe", cuisine: "Seafood", region: "Dolci Cafe", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "145", name: "Rustic Soul Café", cuisine: "Fusion", region: "Rustic Soul Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "146", name: "Amber Wine Bar", cuisine: "Mediterranean", region: "Amber Wine Bar", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "147", name: "Sunset Café Batumi", cuisine: "Asian", region: "Sunset Café Batumi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "148", name: "Café Antique", cuisine: "Seafood", region: "Café Antique", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "149", name: "Charme Tbilisi", cuisine: "Fusion", region: "Charme Tbilisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "150", name: "Café Ninia", cuisine: "Seafood", region: "Café Ninia", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "151", name: "Rustaveli Restaurant", cuisine: "Traditional", region: "Rustaveli Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "152", name: "Gardenia Café", cuisine: "Seafood", region: "Gardenia Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "153", name: "Europe House Café", cuisine: "European", region: "Europe House Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "154", name: "Meama Kitchen", cuisine: "Fusion", region: "Meama Kitchen", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "155", name: "Old Town Grill", cuisine: "Fusion", region: "Old Town Grill", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "156", name: "Puri Guliani", cuisine: "Vegetarian", region: "Puri Guliani", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "157", name: "Ajarian Wine House", cuisine: "Asian", region: "Ajarian Wine House", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "158", name: "Taste of Georgia", cuisine: "Traditional", region: "Taste of Georgia", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "159", name: "Cafe Rustico", cuisine: "Mediterranean", region: "Cafe Rustico", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "160", name: "Beso Restaurant", cuisine: "Georgian", region: "Beso Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "161", name: "Lagidze Water Café", cuisine: "Asian", region: "Lagidze Water Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "162", name: "Gorgasali Café", cuisine: "Fusion", region: "Gorgasali Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "163", name: "Cafe Gallery", cuisine: "Mediterranean", region: "Cafe Gallery", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "164", name: "Sakhli 10", cuisine: "Traditional", region: "Sakhli 10", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "165", name: "Georgian Table", cuisine: "Mediterranean", region: "Georgian Table", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "166", name: "Urban Garden Café", cuisine: "Fusion", region: "Urban Garden Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "167", name: "Delizia Restaurant", cuisine: "Asian", region: "Delizia Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "168", name: "Café de Paris Tbilisi", cuisine: "Georgian", region: "Café de Paris Tbilisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "169", name: "Ninia's Garden", cuisine: "Asian", region: "Ninia's Garden", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "170", name: "Casa della Pasta", cuisine: "Traditional", region: "Casa della Pasta", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "171", name: "Cafe Roma", cuisine: "Traditional", region: "Cafe Roma", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "172", name: "Gvino Underground", cuisine: "Seafood", region: "Gvino Underground", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "173", name: "Kitchen & Wine", cuisine: "Vegetarian", region: "Kitchen & Wine", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "174", name: "Pizzeria Toscana", cuisine: "Mediterranean", region: "Pizzeria Toscana", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "175", name: "Marani Restaurant", cuisine: "European", region: "Marani Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "176", name: "Bagrati Restaurant", cuisine: "Seafood", region: "Bagrati Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "177", name: "Asia Fusion Kutaisi", cuisine: "Georgian", region: "Asia Fusion Kutaisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "178", name: "Utskho Restaurant", cuisine: "Georgian", region: "Utskho Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "179", name: "House of Wine Batumi", cuisine: "Mediterranean", region: "House of Wine Batumi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "180", name: "Fusion Garden", cuisine: "Asian", region: "Fusion Garden", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "181", name: "Cafe Brasserie", cuisine: "Vegetarian", region: "Cafe Brasserie", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "182", name: "Qalaqi Restaurant", cuisine: "Vegetarian", region: "Qalaqi Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "183", name: "Park Lounge Batumi", cuisine: "Georgian", region: "Park Lounge Batumi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "184", name: "Cafe Mandarin", cuisine: "Seafood", region: "Cafe Mandarin", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "185", name: "Brew & Wine", cuisine: "Asian", region: "Brew & Wine", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "186", name: "Vino Underground Kutaisi", cuisine: "Traditional", region: "Vino Underground Kutaisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "187", name: "Mimino Café", cuisine: "European", region: "Mimino Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "188", name: "Ezo Restaurant", cuisine: "Seafood", region: "Ezo Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "189", name: "Khareba Wine Restaurant", cuisine: "European", region: "Khareba Wine Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "190", name: "Firewood Grill", cuisine: "Fusion", region: "Firewood Grill", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "191", name: "Urban Tbilisi Eatery", cuisine: "Vegetarian", region: "Urban Tbilisi Eatery", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "192", name: "Borani Restaurant", cuisine: "Georgian", region: "Borani Restaurant", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "193", name: "Tifliso Garden", cuisine: "European", region: "Tifliso Garden", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "194", name: "Dolci Cafe", cuisine: "Asian", region: "Dolci Cafe", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "195", name: "Rustic Soul Café", cuisine: "Fusion", region: "Rustic Soul Café", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "196", name: "Amber Wine Bar", cuisine: "Georgian", region: "Amber Wine Bar", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "197", name: "Sunset Café Batumi", cuisine: "Asian", region: "Sunset Café Batumi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "198", name: "Café Antique", cuisine: "Traditional", region: "Café Antique", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "199", name: "Charme Tbilisi", cuisine: "Asian", region: "Charme Tbilisi", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  { id: "200", name: "Café Ninia", cuisine: "Seafood", region: "Café Ninia", lat: 0, lng: 0, photo: "/placeholder.jpg", rating: 4.5 },
  // ... (add the next batch of restaurants here)
]; 