export interface Hotel {
  id: string;
  name: string;
  address: string;
  stars: number;
  price_gel: number;
  price_usd: number;
  price_eur: number;
  price_rub: number;
  description: string;
  lat: number | null;
  lng: number | null;
  photo?: string;
  rating?: number;
  region?: string;
  price?: number;
  city?: string;
  featured?: boolean;
}

export const hardcodedHotels = [
  {
    id: "heritage-hotel-and-suites",
    name: "Heritage Hotel And Suites",
    address: "6 Saint Petersburg Street, Tbilisi 0102",
    stars: 4,
    price_gel: 272,
    price_usd: 102,
    price_eur: 94,
    price_rub: 9900,
    description: "A stylish 4-star hotel in the historical heart of Tbilisi. Located in a building recognized as a monument of Georgia's historical and cultural heritage (built in 1897).",
    lat: 0,
    lng: 0,
    photo: "/placeholder.jpg",
    rating: 4.7,
    region: "Tbilisi",
    price: 0,
    city: "Tbilisi",
    featured: true
  },
  {
    id: "radisson-blu-iveria-hotel-tbilisi",
    name: "Radisson Blu Iveria Hotel Tbilisi",
    address: "Radisson Blu Iveria Hotel Tbilisi",
    stars: 4,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "rooms-hotel-tbilisi",
    name: "Rooms Hotel Tbilisi",
    address: "Rooms Hotel Tbilisi",
    stars: 5,
    price_gel: 80,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "stamba-hotel",
    name: "Stamba Hotel",
    address: "Stamba Hotel",
    stars: 3,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "hotel-kopala",
    name: "Hotel Kopala",
    address: "Hotel Kopala",
    stars: 4,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "hotel-tbilisi-tower",
    name: "Hotel Tbilisi Tower",
    address: "Hotel Tbilisi Tower",
    stars: 5,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "iota-hotel-tbilisi",
    name: "Iota Hotel Tbilisi",
    address: "Iota Hotel Tbilisi",
    stars: 5,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "hotel-citrus",
    name: "Hotel Citrus",
    address: "Hotel Citrus",
    stars: 5,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "ambassadori-hotel-tbilisi",
    name: "Ambassadori Hotel Tbilisi",
    address: "Ambassadori Hotel Tbilisi",
    stars: 5,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "tbilisi-marriott-hotel",
    name: "Tbilisi Marriott Hotel",
    address: "Tbilisi Marriott Hotel",
    stars: 4,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "holiday-inn-tbilisi",
    name: "Holiday Inn Tbilisi",
    address: "Holiday Inn Tbilisi",
    stars: 3,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "sheraton-grand-tbilisi-metechi-palace",
    name: "Sheraton Grand Tbilisi Metechi Palace",
    address: "Sheraton Grand Tbilisi Metechi Palace",
    stars: 3,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "hotels-preference-hualing-tbilisi",
    name: "Hotels & Preference Hualing Tbilisi",
    address: "Hotels & Preference Hualing Tbilisi",
    stars: 4,
    price_gel: 80,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "mercure-tbilisi-old-town",
    name: "Mercure Tbilisi Old Town",
    address: "Mercure Tbilisi Old Town",
    stars: 4,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "folk-boutique-hotel",
    name: "Folk Boutique Hotel",
    address: "Folk Boutique Hotel",
    stars: 5,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "hotel-zeg",
    name: "Hotel Zeg",
    address: "Hotel Zeg",
    stars: 5,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "tiflis-palace",
    name: "Tiflis Palace",
    address: "Tiflis Palace",
    stars: 5,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "ibis-styles-tbilisi-center",
    name: "Ibis Styles Tbilisi Center",
    address: "Ibis Styles Tbilisi Center",
    stars: 3,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "ibis-budget-tbilisi-center",
    name: "Ibis Budget Tbilisi Center",
    address: "Ibis Budget Tbilisi Center",
    stars: 3,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "the-grove-design-hotel",
    name: "The Grove Design Hotel",
    address: "The Grove Design Hotel",
    stars: 3,
    price_gel: 200,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "gallery-palace",
    name: "Gallery Palace",
    address: "Gallery Palace",
    stars: 3,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "silk-road-sea-towers-batumi-apart-hotel",
    name: "Silk Road Sea Towers Batumi Apart Hotel",
    address: "Silk Road Sea Towers Batumi Apart Hotel",
    stars: 5,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "hilton-batumi",
    name: "Hilton Batumi",
    address: "Hilton Batumi",
    stars: 3,
    price_gel: 140,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "wyndham-batumi",
    name: "Wyndham Batumi",
    address: "Wyndham Batumi",
    stars: 5,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "le-meridien-batumi",
    name: "Le Méridien Batumi",
    address: "Le Méridien Batumi",
    stars: 4,
    price_gel: 80,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "hotel-intourist-palace",
    name: "Hotel Intourist Palace",
    address: "Hotel Intourist Palace",
    stars: 4,
    price_gel: 80,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi",
    featured: false
  },
  {
    id: "hotel-old-town-batumi",
    name: "Hotel Old Town Batumi",
    address: "Hotel Old Town Batumi",
    stars: 4,
    price_gel: 140,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "sky-tower-hotel-batumi",
    name: "Sky Tower Hotel Batumi",
    address: "Sky Tower Hotel Batumi",
    stars: 5,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "divan-suites-batumi",
    name: "Divan Suites Batumi",
    address: "Divan Suites Batumi",
    stars: 5,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "best-western-premier-batumi",
    name: "Best Western Premier Batumi",
    address: "Best Western Premier Batumi",
    stars: 5,
    price_gel: 200,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "colosseum-marina-hotel",
    name: "Colosseum Marina Hotel",
    address: "Colosseum Marina Hotel",
    stars: 5,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "hotel-aisi-batumi",
    name: "Hotel Aisi Batumi",
    address: "Hotel Aisi Batumi",
    stars: 5,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "mariinsky-boutique-hotel",
    name: "Mariinsky Boutique Hotel",
    address: "Mariinsky Boutique Hotel",
    stars: 5,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi",
    featured: false
  },
  {
    id: "kutaisi-inn",
    name: "Kutaisi Inn",
    address: "Kutaisi Inn",
    stars: 4,
    price_gel: 200,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi",
    featured: false
  },
  {
    id: "hotel-empire-kutaisi",
    name: "Hotel Empire Kutaisi",
    address: "Hotel Empire Kutaisi",
    stars: 3,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi",
    featured: false
  },
  {
    id: "newport-hotel-kutaisi",
    name: "Newport Hotel Kutaisi",
    address: "Newport Hotel Kutaisi",
    stars: 3,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi",
    featured: false
  },
  {
    id: "best-western-kutaisi",
    name: "Best Western Kutaisi",
    address: "Best Western Kutaisi",
    stars: 4,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi",
    featured: false
  },
  {
    id: "hotel-terrace-kutaisi",
    name: "Hotel Terrace Kutaisi",
    address: "Hotel Terrace Kutaisi",
    stars: 5,
    price_gel: 200,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi",
    featured: false
  },
  {
    id: "hotel-argo-kutaisi",
    name: "Hotel Argo Kutaisi",
    address: "Hotel Argo Kutaisi",
    stars: 5,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi",
    featured: false
  },
  {
    id: "west-tower-hotel-kutaisi",
    name: "West Tower Hotel Kutaisi",
    address: "West Tower Hotel Kutaisi",
    stars: 4,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi",
    featured: false
  },
  {
    id: "hotel-california-kutaisi",
    name: "Hotel California Kutaisi",
    address: "Hotel California Kutaisi",
    stars: 4,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi",
    featured: false
  },
  {
    id: "crowne-plaza-borjomi",
    name: "Crowne Plaza Borjomi",
    address: "Crowne Plaza Borjomi",
    stars: 3,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi",
    featured: false
  },
  {
    id: "borjomi-likani-health-spa-centre",
    name: "Borjomi Likani Health & Spa Centre",
    address: "Borjomi Likani Health & Spa Centre",
    stars: 3,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi",
    featured: false
  },
  {
    id: "hotel-victoria-borjomi",
    name: "Hotel Victoria Borjomi",
    address: "Hotel Victoria Borjomi",
    stars: 4,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi",
    featured: false
  },
  {
    id: "hotel-milano-borjomi",
    name: "Hotel Milano Borjomi",
    address: "Hotel Milano Borjomi",
    stars: 3,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi",
    featured: false
  },
  {
    id: "hotel-borjomi-palace",
    name: "Hotel Borjomi Palace",
    address: "Hotel Borjomi Palace",
    stars: 3,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi",
    featured: false
  },
  {
    id: "golden-tulip-borjomi",
    name: "Golden Tulip Borjomi",
    address: "Golden Tulip Borjomi",
    stars: 4,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi",
    featured: false
  },
  {
    id: "hotel-old-borjomi",
    name: "Hotel Old Borjomi",
    address: "Hotel Old Borjomi",
    stars: 4,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi",
    featured: false
  },
  {
    id: "hotel-central-borjomi",
    name: "Hotel Central Borjomi",
    address: "Hotel Central Borjomi",
    stars: 3,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi",
    featured: false
  },
  {
    id: "hotel-rich-borjomi",
    name: "Hotel Rich Borjomi",
    address: "Hotel Rich Borjomi",
    stars: 3,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi"
  },
  {
    id: "borjomi-cottages",
    name: "Borjomi Cottages",
    address: "Borjomi Cottages",
    stars: 3,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Borjomi"
  },
  {
    id: "bakuriani-inn",
    name: "Bakuriani Inn",
    address: "Bakuriani Inn",
    stars: 5,
    price_gel: 80,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Bakuriani"
  },
  {
    id: "crystal-hotel-spa-bakuriani",
    name: "Crystal Hotel & SPA Bakuriani",
    address: "Crystal Hotel & SPA Bakuriani",
    stars: 4,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Bakuriani"
  },
  {
    id: "hotel-crystal",
    name: "Hotel Crystal",
    address: "Hotel Crystal",
    stars: 3,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "orbi-palace-hotel-bakuriani",
    name: "Orbi Palace Hotel Bakuriani",
    address: "Orbi Palace Hotel Bakuriani",
    stars: 5,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Bakuriani"
  },
  {
    id: "hotel-prima-bakuriani",
    name: "Hotel Prima Bakuriani",
    address: "Hotel Prima Bakuriani",
    stars: 3,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Bakuriani"
  },
  {
    id: "hotel-mgzavrebi",
    name: "Hotel Mgzavrebi",
    address: "Hotel Mgzavrebi",
    stars: 4,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-villa-palace-bakuriani",
    name: "Hotel Villa Palace Bakuriani",
    address: "Hotel Villa Palace Bakuriani",
    stars: 5,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Bakuriani"
  },
  {
    id: "hotel-eden-bakuriani",
    name: "Hotel Eden Bakuriani",
    address: "Hotel Eden Bakuriani",
    stars: 4,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Bakuriani"
  },
  {
    id: "hotel-king-david",
    name: "Hotel King David",
    address: "Hotel King David",
    stars: 4,
    price_gel: 80,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-plaza-tbilisi",
    name: "Hotel Plaza Tbilisi",
    address: "Hotel Plaza Tbilisi",
    stars: 3,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "central-inn-batumi",
    name: "Central Inn Batumi",
    address: "Central Inn Batumi",
    stars: 5,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi"
  },
  {
    id: "blue-sky-kutaisi-hotel",
    name: "Blue Sky Kutaisi Hotel",
    address: "Blue Sky Kutaisi Hotel",
    stars: 5,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi"
  },
  {
    id: "royal-park-hotel",
    name: "Royal Park Hotel",
    address: "Royal Park Hotel",
    stars: 4,
    price_gel: 200,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "city-center-guesthouse",
    name: "City Center Guesthouse",
    address: "City Center Guesthouse",
    stars: 5,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "lakeview-hotel-tbilisi",
    name: "Lakeview Hotel Tbilisi",
    address: "Lakeview Hotel Tbilisi",
    stars: 4,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "seaside-resort-batumi",
    name: "Seaside Resort Batumi",
    address: "Seaside Resort Batumi",
    stars: 3,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi"
  },
  {
    id: "urban-lodge-kutaisi",
    name: "Urban Lodge Kutaisi",
    address: "Urban Lodge Kutaisi",
    stars: 4,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi"
  },
  {
    id: "grand-palace-tbilisi",
    name: "Grand Palace Tbilisi",
    address: "Grand Palace Tbilisi",
    stars: 4,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "modern-inn-batumi",
    name: "Modern Inn Batumi",
    address: "Modern Inn Batumi",
    stars: 3,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi"
  },
  {
    id: "luxury-stay-kutaisi",
    name: "Luxury Stay Kutaisi",
    address: "Luxury Stay Kutaisi",
    stars: 5,
    price_gel: 80,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi"
  },
  {
    id: "sunset-hotel-tbilisi",
    name: "Sunset Hotel Tbilisi",
    address: "Sunset Hotel Tbilisi",
    stars: 3,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "white-pearl-batumi",
    name: "White Pearl Batumi",
    address: "White Pearl Batumi",
    stars: 5,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi"
  },
  {
    id: "mountain-view-kutaisi-hotel",
    name: "Mountain View Kutaisi Hotel",
    address: "Mountain View Kutaisi Hotel",
    stars: 5,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi"
  },
  {
    id: "heritage-hotel",
    name: "Heritage Hotel",
    address: "Heritage Hotel",
    stars: 3,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "skyline-hotel",
    name: "Skyline Hotel",
    address: "Skyline Hotel",
    stars: 4,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "elite-hotel",
    name: "Elite Hotel",
    address: "Elite Hotel",
    stars: 3,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "dreamland-inn",
    name: "Dreamland Inn",
    address: "Dreamland Inn",
    stars: 4,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "peaceful-stay-hotel",
    name: "Peaceful Stay Hotel",
    address: "Peaceful Stay Hotel",
    stars: 3,
    price_gel: 140,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "amber-hotel-tbilisi",
    name: "Amber Hotel Tbilisi",
    address: "Amber Hotel Tbilisi",
    stars: 4,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-horizon",
    name: "Hotel Horizon",
    address: "Hotel Horizon",
    stars: 5,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "comfort-suites-kutaisi",
    name: "Comfort Suites Kutaisi",
    address: "Comfort Suites Kutaisi",
    stars: 3,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi"
  },
  {
    id: "hotel-botanica",
    name: "Hotel Botanica",
    address: "Hotel Botanica",
    stars: 3,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "grand-avenue-hotel",
    name: "Grand Avenue Hotel",
    address: "Grand Avenue Hotel",
    stars: 4,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-riverside",
    name: "Hotel Riverside",
    address: "Hotel Riverside",
    stars: 4,
    price_gel: 140,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "capital-inn",
    name: "Capital Inn",
    address: "Capital Inn",
    stars: 3,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "urban-vibe-hotel",
    name: "Urban Vibe Hotel",
    address: "Urban Vibe Hotel",
    stars: 4,
    price_gel: 140,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "georgia-elite-suites",
    name: "Georgia Elite Suites",
    address: "Georgia Elite Suites",
    stars: 5,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "royal-suites-tbilisi",
    name: "Royal Suites Tbilisi",
    address: "Royal Suites Tbilisi",
    stars: 5,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "diamond-palace-hotel",
    name: "Diamond Palace Hotel",
    address: "Diamond Palace Hotel",
    stars: 4,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "central-line-inn",
    name: "Central Line Inn",
    address: "Central Line Inn",
    stars: 4,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hilltop-hotel-kutaisi",
    name: "Hilltop Hotel Kutaisi",
    address: "Hilltop Hotel Kutaisi",
    stars: 4,
    price_gel: 140,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi"
  },
  {
    id: "black-sea-inn-batumi",
    name: "Black Sea Inn Batumi",
    address: "Black Sea Inn Batumi",
    stars: 3,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Batumi"
  },
  {
    id: "golden-view-hotel",
    name: "Golden View Hotel",
    address: "Golden View Hotel",
    stars: 4,
    price_gel: 200,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "panorama-suites",
    name: "Panorama Suites",
    address: "Panorama Suites",
    stars: 5,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "aurora-hotel",
    name: "Aurora Hotel",
    address: "Aurora Hotel",
    stars: 3,
    price_gel: 80,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "silver-star-hotel",
    name: "Silver Star Hotel",
    address: "Silver Star Hotel",
    stars: 3,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "lavender-boutique-hotel",
    name: "Lavender Boutique Hotel",
    address: "Lavender Boutique Hotel",
    stars: 5,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "rose-garden-hotel",
    name: "Rose Garden Hotel",
    address: "Rose Garden Hotel",
    stars: 3,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-magnolia",
    name: "Hotel Magnolia",
    address: "Hotel Magnolia",
    stars: 3,
    price_gel: 110,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "emerald-hotel",
    name: "Emerald Hotel",
    address: "Emerald Hotel",
    stars: 5,
    price_gel: 140,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-legacy",
    name: "Hotel Legacy",
    address: "Hotel Legacy",
    stars: 3,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "green-valley-hotel",
    name: "Green Valley Hotel",
    address: "Green Valley Hotel",
    stars: 5,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "cityscape-hotel",
    name: "Cityscape Hotel",
    address: "Cityscape Hotel",
    stars: 3,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "harbor-view-hotel",
    name: "Harbor View Hotel",
    address: "Harbor View Hotel",
    stars: 4,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "galaxy-hotel-kutaisi",
    name: "Galaxy Hotel Kutaisi",
    address: "Galaxy Hotel Kutaisi",
    stars: 4,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi"
  },
  {
    id: "sapphire-hotel",
    name: "Sapphire Hotel",
    address: "Sapphire Hotel",
    stars: 4,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-meridian",
    name: "Hotel Meridian",
    address: "Hotel Meridian",
    stars: 3,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "topaz-hotel",
    name: "Topaz Hotel",
    address: "Topaz Hotel",
    stars: 4,
    price_gel: 130,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "luxury-palace",
    name: "Luxury Palace",
    address: "Luxury Palace",
    stars: 5,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-eden-garden",
    name: "Hotel Eden Garden",
    address: "Hotel Eden Garden",
    stars: 5,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-diamond-peak",
    name: "Hotel Diamond Peak",
    address: "Hotel Diamond Peak",
    stars: 4,
    price_gel: 150,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "ruby-inn",
    name: "Ruby Inn",
    address: "Ruby Inn",
    stars: 5,
    price_gel: 180,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "sunrise-hotel",
    name: "Sunrise Hotel",
    address: "Sunrise Hotel",
    stars: 4,
    price_gel: 120,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-amethyst",
    name: "Hotel Amethyst",
    address: "Hotel Amethyst",
    stars: 4,
    price_gel: 160,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "classic-stay",
    name: "Classic Stay",
    address: "Classic Stay",
    stars: 5,
    price_gel: 200,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-landmark",
    name: "Hotel Landmark",
    address: "Hotel Landmark",
    stars: 4,
    price_gel: 200,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-nova-kutaisi",
    name: "Hotel Nova Kutaisi",
    address: "Hotel Nova Kutaisi",
    stars: 5,
    price_gel: 140,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Kutaisi"
  },
  {
    id: "cozy-corner-hotel",
    name: "Cozy Corner Hotel",
    address: "Cozy Corner Hotel",
    stars: 4,
    price_gel: 95,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Comfortable hotel offering modern amenities, convenient location, and excellent service for both tourists and business travelers.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-120",
    name: "Hotel 120",
    address: "120 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-121",
    name: "Hotel 121",
    address: "121 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-122",
    name: "Hotel 122",
    address: "122 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-123",
    name: "Hotel 123",
    address: "123 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-124",
    name: "Hotel 124",
    address: "124 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-125",
    name: "Hotel 125",
    address: "125 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-126",
    name: "Hotel 126",
    address: "126 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-127",
    name: "Hotel 127",
    address: "127 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-128",
    name: "Hotel 128",
    address: "128 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-129",
    name: "Hotel 129",
    address: "129 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-130",
    name: "Hotel 130",
    address: "130 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-131",
    name: "Hotel 131",
    address: "131 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-132",
    name: "Hotel 132",
    address: "132 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-133",
    name: "Hotel 133",
    address: "133 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-134",
    name: "Hotel 134",
    address: "134 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-135",
    name: "Hotel 135",
    address: "135 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-136",
    name: "Hotel 136",
    address: "136 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-137",
    name: "Hotel 137",
    address: "137 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-138",
    name: "Hotel 138",
    address: "138 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-139",
    name: "Hotel 139",
    address: "139 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-140",
    name: "Hotel 140",
    address: "140 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-141",
    name: "Hotel 141",
    address: "141 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-142",
    name: "Hotel 142",
    address: "142 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-143",
    name: "Hotel 143",
    address: "143 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-144",
    name: "Hotel 144",
    address: "144 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-145",
    name: "Hotel 145",
    address: "145 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-146",
    name: "Hotel 146",
    address: "146 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-147",
    name: "Hotel 147",
    address: "147 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-148",
    name: "Hotel 148",
    address: "148 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-149",
    name: "Hotel 149",
    address: "149 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-150",
    name: "Hotel 150",
    address: "150 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-151",
    name: "Hotel 151",
    address: "151 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-152",
    name: "Hotel 152",
    address: "152 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-153",
    name: "Hotel 153",
    address: "153 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-154",
    name: "Hotel 154",
    address: "154 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-155",
    name: "Hotel 155",
    address: "155 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-156",
    name: "Hotel 156",
    address: "156 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-157",
    name: "Hotel 157",
    address: "157 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-158",
    name: "Hotel 158",
    address: "158 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-159",
    name: "Hotel 159",
    address: "159 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-160",
    name: "Hotel 160",
    address: "160 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-161",
    name: "Hotel 161",
    address: "161 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-162",
    name: "Hotel 162",
    address: "162 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-163",
    name: "Hotel 163",
    address: "163 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-164",
    name: "Hotel 164",
    address: "164 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-165",
    name: "Hotel 165",
    address: "165 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-166",
    name: "Hotel 166",
    address: "166 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-167",
    name: "Hotel 167",
    address: "167 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-168",
    name: "Hotel 168",
    address: "168 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-169",
    name: "Hotel 169",
    address: "169 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-170",
    name: "Hotel 170",
    address: "170 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-171",
    name: "Hotel 171",
    address: "171 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-172",
    name: "Hotel 172",
    address: "172 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-173",
    name: "Hotel 173",
    address: "173 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-174",
    name: "Hotel 174",
    address: "174 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-175",
    name: "Hotel 175",
    address: "175 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-176",
    name: "Hotel 176",
    address: "176 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-177",
    name: "Hotel 177",
    address: "177 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-178",
    name: "Hotel 178",
    address: "178 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-179",
    name: "Hotel 179",
    address: "179 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-180",
    name: "Hotel 180",
    address: "180 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-181",
    name: "Hotel 181",
    address: "181 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-182",
    name: "Hotel 182",
    address: "182 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-183",
    name: "Hotel 183",
    address: "183 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-184",
    name: "Hotel 184",
    address: "184 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-185",
    name: "Hotel 185",
    address: "185 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-186",
    name: "Hotel 186",
    address: "186 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-187",
    name: "Hotel 187",
    address: "187 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-188",
    name: "Hotel 188",
    address: "188 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-189",
    name: "Hotel 189",
    address: "189 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-190",
    name: "Hotel 190",
    address: "190 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-191",
    name: "Hotel 191",
    address: "191 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-192",
    name: "Hotel 192",
    address: "192 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-193",
    name: "Hotel 193",
    address: "193 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-194",
    name: "Hotel 194",
    address: "194 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-195",
    name: "Hotel 195",
    address: "195 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-196",
    name: "Hotel 196",
    address: "196 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-197",
    name: "Hotel 197",
    address: "197 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-198",
    name: "Hotel 198",
    address: "198 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-199",
    name: "Hotel 199",
    address: "199 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  },
  {
    id: "hotel-200",
    name: "Hotel 200",
    address: "200 Example Street, Tbilisi",
    stars: 3,
    price_gel: 100,
    price_usd: null,
    price_eur: null,
    price_rub: null,
    description: "Placeholder hotel for demonstration purposes.",
    lat: null,
    lng: null,
    city: "Tbilisi"
  }
];