name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Remove incompatible routes for static build
        run: |
          rm -rf app/api
          rm -rf app/hotel

      - name: Build the Next.js application
        run: pnpm run build

      - name: Sync Capacitor project
        run: pnpm exec cap sync android

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Build debug APK
        run: ./android/gradlew -p android assembleDebug

      - name: Rename APK
        run: mv android/app/build/outputs/apk/debug/app-debug.apk public/GeorgiaStay.apk

      - name: Commit APK
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/GeorgiaStay.apk
          git commit -m "build: Add/update GeorgiaStay.apk" || echo "No changes to commit"
          git push

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: GeorgiaStay-apk
          path: public/GeorgiaStay.apk 